name: bompare
description: Bill-of-materials comparison tool.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.1
  path: ^1.7.0
  glob: ^2.0.1
  archive: ^3.1.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.17.5
  coverage: ^1.0.3
  mockito: ^5.0.10
